# Prática — Teste 01 – Atividade Valendo 40% da Média do Bimestre

##**Alunos**: Peterson Alves Pereira & Gabriel Yuji Shimoda Vieira

## Questão 01 (1.0)
a) Considere o dataset abaixo em que cada linha representa uma transação. Explique qual é a unidade de análise e identifique a variável-alvo.

b) Crie o DataFrame e separe X e y, rremovendo as colunas que não devem ser utilizadas como variáveis explicativas no modelo.


    'transacao_id': [1,2,3,4,5,6,7,8],
    'cliente_id':   [1,1,2,2,3,3,4,4],
    'valor_compra': [100,200,50,80,300,150,400,500],
    'tempo_cliente':[12,12,6,6,24,24,36,36],
    'valor_estornado': [0,200,0,0,300,0,0,500],
    'fraude':       [0,1,0,0,1,0,0,1]

### RESPOSTA

Item (1A)

A unidade de análise é a transação. Cada linha do dataset representa um evento de compra individual, identificado pela coluna transacao_id. A variável alvo é a coluna fraude. É ela que queremos prever (se aquela transação específica é fraudulenta ou não).

In [58]:
# RESPOSTA Item (1B)
# Seu código abaixo:

import pandas as pd

dados = {
    'transacao_id': [1,2,3,4,5,6,7,8],
    'cliente_id': [1,1,2,2,3,3,4,4],
    'valor_compra': [100,200,50,80,300,150,400,500],
    'tempo_cliente':[12,12,6,6,24,24,36,36],
    'valor_estornado': [0,200,0,0,300,0,0,500],
    'fraude': [0,1,0,0,1,0,0,1]
}
df = pd.DataFrame(dados)

X = df.drop(columns=['transacao_id', 'cliente_id', 'valor_estornado', 'fraude'])
y = df['fraude']

print("--- Variáveis Explicativas (X) ---")
display(X)

print("\n--- Variável-Alvo (y) ---")
print(y.tolist())

--- Variáveis Explicativas (X) ---

   valor_compra  tempo_cliente
0           100             12
1           200             12
2            50              6
3            80              6
4           300             24
5           150             24
6           400             36
7           500             36

--- Variável-Alvo (y) ---
[0, 1, 0, 0, 1, 0, 0, 1]

## Questão 02 (1.0)

a) Considere novamente o dataset abaixo. Se o problema for reformulado para o nível de cliente, explique como muda a unidade de análise, a variável-alvo e as variáveis explicativas.

b) Crie o DataFrame abaixo e, em seguida, agregue os dados por cliente_id, de forma que cada linha represente um cliente.
Construa um novo DataFrame com:

soma de valor_compra

quantidade de transações

manter tempo_cliente utilizando o primeiro valor por cliente

variável-alvo: indicar se o cliente teve ao menos uma fraude (valor 1 se sim, 0 caso contrário)

Não utilize a coluna valor_estornado na construção das variáveis explicativas.

Depois, separe X e y.

    'transacao_id': [1,2,3,4,5,6,7,8],
    'cliente_id':   [1,1,2,2,3,3,4,4],
    'valor_compra': [100,200,50,80,300,150,400,500],
    'tempo_cliente':[12,12,6,6,24,24,36,36],
    'valor_estornado': [0,200,0,0,300,0,0,500],
    'fraude':       [0,1,0,0,1,0,0,1]

### RESPOSTA

Item (2A)

Ao mudar para o nível de cliente, a unidade de análise passa a ser o indivíduo (cliente_id), e não mais cada transação isolada. A variável-alvo agora indica se o cliente possui histórico de fraude (1 se ele teve pelo menos uma transação fraudulenta, 0 caso contrário). As variáveis explicativas precisam ser agregadas por cliente, como a soma total de compras e a quantidade de transações realizadas por cada um.

In [47]:
# RESPOSTA Item (2B)
# Seu código abaixo:

import pandas as pd

dados = {
    'transacao_id': [1,2,3,4,5,6,7,8],
    'cliente_id': [1,1,2,2,3,3,4,4],
    'valor_compra': [100,200,50,80,300,150,400,500],
    'tempo_cliente':[12,12,6,6,24,24,36,36],
    'valor_estornado': [0,200,0,0,300,0,0,500],
    'fraude': [0,1,0,0,1,0,0,1]
}
df_transacional = pd.DataFrame(dados)

df_agregado = df_transacional.groupby('cliente_id').agg({
    'valor_compra': 'sum',
    'transacao_id': 'count',
    'tempo_cliente': 'first',
    'fraude': 'max'
}).rename(columns={
    'valor_compra': 'soma_valor_compra',
    'transacao_id': 'quantidade_transacoes'
}).reset_index()

X = df_agregado.drop(columns=['cliente_id', 'fraude'])
y = df_agregado['fraude']


print("--- DataFrame Agregado (Nível Cliente) ---")
display(df_agregado)
print("\n--- Variáveis Explicativas (X) ---")
display(X)

print("\n--- Variável-Alvo (y) ---")
print(y.tolist())

--- DataFrame Agregado (Nível Cliente) ---

   cliente_id  soma_valor_compra  quantidade_transacoes  tempo_cliente  fraude
0           1                300                      2             12       1
1           2                130                      2              6       0
2           3                450                      2             24       1
3           4                900                      2             36       1

--- Variáveis Explicativas (X) ---

   soma_valor_compra  quantidade_transacoes  tempo_cliente
0                300                      2             12
1                130                      2              6
2                450                      2             24
3                900                      2             36

--- Variável-Alvo (y) ---
[1, 0, 1, 1]

## Questão 03 (1.0)

a) O que é construção de atributos em análise preditiva?

b) No dataset abaixo, crie uma nova variável chamada valor_medio_por_compra dividindo o total gasto pela quantidade de compras.

    'cliente_id': [1,2,3,4],
    'total_gasto': [1000, 2000, 1500, 3000],
    'qtd_compras': [5, 10, 3, 6]

### RESPOSTA

Item (3A)

A construção de atributos  consiste em criar novas variáveis a partir das existentes para capturar relações que facilitem o aprendizado do modelo. O objetivo é transformar dados brutos em colunas que reflitam melhor o comportamento do fenômeno estudado.

In [48]:
# RESPOSTA Item (3B)
# Seu código abaixo:

import pandas as pd

dados_3b = {
    'cliente_id': [1,2,3,4],
    'total_gasto': [1000, 2000, 1500, 3000],
    'qtd_compras': [5, 10, 3, 6]
}
df_3b = pd.DataFrame(dados_3b)

df_3b['valor_medio_por_compra'] = df_3b['total_gasto'] / df_3b['qtd_compras']

print("--- Questão 3B ---")
display(df_3b)

--- Questão 3B ---

   cliente_id  total_gasto  qtd_compras  valor_medio_por_compra
0           1         1000            5                   200.0
1           2         2000           10                   200.0
2           3         1500            3                   500.0
3           4         3000            6                   500.0

## Questão 04 (1.0)

a) O que é codificação de variáveis categóricas e por que ela é necessária em modelos preditivos?

b) No dataset abaixo, aplique codificação One-Hot na variável tipo_pagamento.

    'cliente_id': [1,2,3,4],
    'tipo_pagamento': ['cartao', 'boleto', 'pix', 'cartao']

### RESPOSTA

Item (4A)

A codificação de variáveis categóricas é o processo de transformar valores categóricos em valores numéricos para que possam ser utilizados por algoritmos de aprendizado de máquina. Ela atua como um "tradutor" da linguagem humana para a linguagem de máquina. Ela é necessária porque a maioria dos modelos matemáticos não conseguem realizar cálculos e encontrar padrões se os dados estiverem em formato de texto.

In [49]:
# RESPOSTA Item (4B)
# Seu código abaixo:

import pandas as pd

dados_4b = {
    'cliente_id': [1,2,3,4],
    'tipo_pagamento': ['cartao', 'boleto', 'pix', 'cartao']
}
df_4b = pd.DataFrame(dados_4b)

df_4b_final = pd.get_dummies(df_4b, columns=['tipo_pagamento'], prefix='pagto')

print("--- Questão 4B (One-Hot Encoding) ---")
display(df_4b_final)

--- Questão 4B (One-Hot Encoding) ---

   cliente_id  pagto_boleto  pagto_cartao  pagto_pix
0           1         False          True      False
1           2          True         False      False
2           3         False         False       True
3           4         False          True      False

## Questão 05 (1.0)

a) O que é codificação ordinal e em que tipo de variável ela deve ser aplicada?

b) No dataset abaixo, aplique codificação ordinal na variável nivel_cliente, considerando a ordem: baixo < medio < alto.

    'cliente_id': [1,2,3,4],
    'nivel_cliente': ['baixo', 'alto', 'medio', 'baixo']

### RESPOSTA

Item (5A)

A codificação ordinal é simplesmente trocar categorias de texto por números em sequência (como 1, 2 e 3) para mostrar para o modelo que existe uma ordem de 'tamanho' ou 'importância' entre elas. Ela deve ser aplicada em variáveis categóricas ordinais, ou seja, aquelas que possuem uma ordem lógica ou hierarquia intrínseca (ex: tamanhos P/M/G, níveis de satisfação ou escolaridade). Se a ordem não importar (como 'cor do carro'), o ideal é usar One-Hot.

In [50]:
# RESPOSTA Item (5B)
# Seu código abaixo:

import pandas as pd

dados_5b = {
    'cliente_id': [1,2,3,4],
    'nivel_cliente': ['baixo', 'alto', 'medio', 'baixo']
}
df_5b = pd.DataFrame(dados_5b)

ordem = {
    'baixo': 1,
    'medio': 2,
    'alto': 3
}

df_5b['nivel_cliente_codificado'] = df_5b['nivel_cliente'].map(ordem)

print("--- Questão 5B (Codificação Ordinal) ---")
display(df_5b)

--- Questão 5B (Codificação Ordinal) ---

   cliente_id nivel_cliente  nivel_cliente_codificado
0           1         baixo                         1
1           2          alto                         3
2           3         medio                         2
3           4         baixo                         1

## Questão 06 (1.0)

a) O que é normalização e qual seu objetivo no contexto de modelos preditivos?

b) No dataset abaixo, aplique normalização (Min-Max) na variável renda, transformando os valores para o intervalo [0,1].

    'cliente_id': [1,2,3,4],
    'renda': [2000, 5000, 3000, 4000]

### RESPOSTA

Item (6A)

A normalização é um tipo de escalonamento. Ela consiste em pegar valores distintos e reescalá-los em uma faixa numérica ou intervalo fixo, como entre 0 e 1. Sendo assim, o menor valor da variável passa a ser 0 e o maior 1, os demais são posicionados proporcionalemente entre este intervalor, isso reduz a complexidade de cálculo para o modelo. O objetivo principal é evitar que variáveis com valores absolutos muito grandes dominem algoritmos baseados em distância ou gradiente, colocando todos os atributos na mesma escala de grandeza e facilitando o aprendizado do modelo

In [51]:
# RESPOSTA Item (6B)
# Seu código abaixo:

import pandas as pd

dados_6b = {
    'cliente_id': [1,2,3,4],
    'renda': [2000, 5000, 3000, 4000]
}
df_6b = pd.DataFrame(dados_6b)

min_renda = df_6b['renda'].min()
max_renda = df_6b['renda'].max()

df_6b['renda_normalizada'] = (df_6b['renda'] - min_renda) / (max_renda - min_renda)

print("--- Questão 6B (Normalização Min-Max) ---")
display(df_6b)

--- Questão 6B (Normalização Min-Max) ---

   cliente_id  renda  renda_normalizada
0           1   2000           0.000000
1           2   5000           1.000000
2           3   3000           0.333333
3           4   4000           0.666667

## Questão 07 (1.0)

a) O que é padronização e qual a diferença em relação à normalização?

b) No dataset abaixo, aplique padronização (Z-score) na variável renda.

    'cliente_id': [1,2,3,4],
    'renda': [2000, 5000, 3000, 4000]

### RESPOSTA

Item (7A)

 A padronização é uma forma de escalonamento que visa transformar as variáveis para uma mesma escala. Assim como na normalização, seu objetivo é garantir que nenhuma feature domine o modelo. A principal diferença em relação à normalização é que a padronização transforma os valores de uma variável para que tenham média 0 e desvio padrão 1. Dessa forma, cada valor passa a representar quantos desvios padrão ele está acima ou abaixo da média da variável.

In [52]:
# RESPOSTA Item (7B)
# Seu código abaixo:
import pandas as pd

dados_7b = {
    'cliente_id': [1,2,3,4],
    'renda': [2000, 5000, 3000, 4000]
}
df_7b = pd.DataFrame(dados_7b)

media_renda = df_7b['renda'].mean()
desvio_renda = df_7b['renda'].std(ddof=0)

df_7b['renda_padronizada'] = (df_7b['renda'] - media_renda) / desvio_renda

print("--- Questão 7B (Padronização Z-score) ---")
display(df_7b)

--- Questão 7B (Padronização Z-score) ---

   cliente_id  renda  renda_padronizada
0           1   2000          -1.341641
1           2   5000           1.341641
2           3   3000          -0.447214
3           4   4000           0.447214

## Questão 08 (1.0)

a) O que é seleção de atributos e qual seu objetivo em análise preditiva?

b) No dataset abaixo, identifique e remova as variáveis que não devem ser utilizadas no modelo e, em seguida, separe X e y.

    'cliente_id': [1,2,3,4],
    'idade': [25, 40, 35, 50],
    'renda_mensal': [2000, 5000, 3000, 4000],
    'renda_anual': [24000, 60000, 36000, 48000],
    'inadimplente': [0,1,0,1]

### RESPOSTA

Item (8A)

A seleção de atributos é uma etapa da engenharia de atributos que consite em indentificar e manter apenas as variáveis mais relevantes, removendo as que são redundantes e que pouco contribuem para o modelo preditivo. Seu objetivo é preservar a maior parte da informação relevante para o modelo.

In [53]:
# RESPOSTA Item (8B)
# Seu código abaixo:

import pandas as pd

dados_8b = {
    'cliente_id': [1,2,3,4],
    'idade': [25, 40, 35, 50],
    'renda_mensal': [2000, 5000, 3000, 4000],
    'renda_anual': [24000, 60000, 36000, 48000],
    'inadimplente': [0,1,0,1]
}
df_8b = pd.DataFrame(dados_8b)

X = df_8b.drop(columns=['cliente_id', 'renda_anual', 'inadimplente'])
y = df_8b['inadimplente']

print("--- Questão 8B (Seleção de Atributos) ---")
print("\nVariáveis explicativas (X) selecionadas:")
display(X)

print("\nVariável-alvo (y):")
print(y.tolist())

--- Questão 8B (Seleção de Atributos) ---

Variáveis explicativas (X) selecionadas:

   idade  renda_mensal
0     25          2000
1     40          5000
2     35          3000
3     50          4000

Variável-alvo (y):
[0, 1, 0, 1]

## Questão 09 (1.0)

a) Como a correlação pode ser utilizada no processo de seleção de atributos?

b) Crie o DataFrame abaixo, calcule a matriz de correlação e, com base nela, identifique qual variável pode ser removida por redundância. Em seguida, remova essa variável, separe X e y e exiba o resultado.

    "idade": [22, 25, 28, 35, 45, 52, 30, 40],
    "renda": [2500, 3200, 4100, 5200, 7000, 8200, 4500, 6100],
    "anos_estudo": [12, 14, 16, 18, 16, 14, 15, 17],
    "tempo_empresa": [1, 2, 3, 6, 10, 15, 4, 8],
    "salario": [3000, 3500, 4500, 6000, 7200, 8000, 5000, 6500]

### RESPOSTA

Item (9A)

A correlação mede o grau de relação (geralmente linear) entre variáveis, sendo útil na seleção de atributos para identificar quais features têm maior associação com a variável-alvo e quais são redundantes entre si.

In [59]:
# RESPOSTA Item (9B)
# Seu código abaixo:

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

dados_9b = {
    "idade": [22, 25, 28, 35, 45, 52, 30, 40],
    "renda": [2500, 3200, 4100, 5200, 7000, 8200, 4500, 6100],
    "anos_estudo": [12, 14, 16, 18, 16, 14, 15, 17],
    "tempo_empresa": [1, 2, 3, 6, 10, 15, 4, 8],
    "salario": [3000, 3500, 4500, 6000, 7200, 8000, 5000, 6500]
}
df_9b = pd.DataFrame(dados_9b)

matriz_correlacao = df_9b.corr()

print("--- Matriz de Correlação ---")
display(matriz_correlacao)

y = df_9b['salario']

X = df_9b.drop(columns=['salario', 'renda', 'idade'])

print("\nVariáveis explicativas (X) após remover as redundâncias:")
display(X)

print("\nVariável-alvo (y):")
print(y.tolist())

--- Matriz de Correlação ---

                  idade     renda  anos_estudo  tempo_empresa   salario
idade          1.000000  0.995857     0.329531       0.991892  0.982806
renda          0.995857  1.000000     0.380894       0.982528  0.991517
anos_estudo    0.329531  0.380894     1.000000       0.234710  0.477348
tempo_empresa  0.991892  0.982528     0.234710       1.000000  0.959233
salario        0.982806  0.991517     0.477348       0.959233  1.000000

Variáveis explicativas (X) após remover as redundâncias:

   anos_estudo  tempo_empresa
0           12              1
1           14              2
2           16              3
3           18              6
4           16             10
5           14             15
6           15              4
7           17              8

Variável-alvo (y):
[3000, 3500, 4500, 6000, 7200, 8000, 5000, 6500]

## Questão 10 (1.0)

a) O que é informação mútua e como ela pode ser utilizada na seleção de atributos?

b) Crie o DataFrame abaixo, calcule a informação mútua entre as variáveis explicativas e a variável-alvo e identifique qual variável apresenta menor relevância. Em seguida, remova essa variável, separe X e y e exiba o resultado.

    "temperatura": [15,18,21,24,27,30,33,36,39],
    "marketing": [100,120,140,160,180,200,220,240,260],
    "renda_regiao": [2000,2100,2200,2300,2400,2500,2600,2700,2800],
    "vendas_sorvete": [180,250,330,420,520,630,750,880,1020]

### RESPOSTA

Item (10A)

A informação mútua é uma medida que quantifica o quanto uma variável reduz a incerteza sobre outra, indicando o grau de dependência entre elas. Na seleção de atributos, ela é utilizada para identificar quais variáveis possuem maior relação com a variável-alvo, permitindo selecionar as mais informativas, inclusive quando existem relações não lineares.

In [55]:
# RESPOSTA Item (10B)
# Seu código abaixo:

import pandas as pd
from sklearn.feature_selection import mutual_info_regression

dados_10b = {
   "temperatura": [15,18,21,24,27,30,33,36,39],
"marketing": [100,120,140,160,180,200,220,240,260],
"renda_regiao": [2000,2100,2200,2300,2400,2500,2600,2700,2800],
"vendas_sorvete": [180,250,330,420,520,630,750,880,1020]
}
df_10b = pd.DataFrame(dados_10b)

X_total = df_10b.drop(columns=['vendas_sorvete'])
y_alvo = df_10b['vendas_sorvete']


mi = mutual_info_regression(X_total, y_alvo, random_state=42)

mi_df = pd.DataFrame({'Atributo': X_total.columns, 'Informação Mútua': mi})
print("--- Informação Mútua (MI) ---")
display(mi_df.sort_values(by='Informação Mútua', ascending=False))

X_final = X_total.drop(columns=['renda_regiao'])

print("\nVariáveis explicativas (X) após remover a menor relevância (renda_regiao):")
display(X_final)

print("\nVariável-alvo (y):")
print(y_alvo.tolist())

--- Informação Mútua (MI) ---

       Atributo  Informação Mútua
0   temperatura          0.801190
1     marketing          0.801190
2  renda_regiao          0.764153

Variáveis explicativas (X) após remover a menor relevância (renda_regiao):

   temperatura  marketing
0           15        100
1           18        120
2           21        140
3           24        160
4           27        180
5           30        200
6           33        220
7           36        240
8           39        260

Variável-alvo (y):
[180, 250, 330, 420, 520, 630, 750, 880, 1020]