# Prática — Teste 01 – Atividade Valendo 40% da Média do Bimestre

## Questão 01 (1.0)
a) Considere o dataset abaixo em que cada linha representa uma transação. Explique qual é a unidade de análise e identifique a variável-alvo.  


b) Crie o DataFrame e separe X e y, rremovendo as colunas que não devem ser utilizadas como variáveis explicativas no modelo.


    'transacao_id': [1,2,3,4,5,6,7,8],
    'cliente_id':   [1,1,2,2,3,3,4,4],
    'valor_compra': [100,200,50,80,300,150,400,500],
    'tempo_cliente':[12,12,6,6,24,24,36,36],
    'valor_estornado': [0,200,0,0,300,0,0,500],
    'fraude':       [0,1,0,0,1,0,0,1]

### RESPOSTA

Item (1A)
A unidade de análise é uma compra/transação realizada pelo cliente. A variável-alvo é a fraude

In [ ]:
# RESPOSTA Item (1B)
# Seu código abaixo:

import pandas as pd

# Criando o DataFrame
df1 = pd.DataFrame({
    'transacao_id': [1,2,3,4,5,6,7,8],
    'cliente_id': [1,1,2,2,3,3,4,4],
    'valor_compra': [100,200,50,80,300,150,400,500],
    'tempo_cliente': [12,12,6,6,24,24,36,36],
    'valor_estornado': [0,200,0,0,300,0,0,500],
    'fraude': [0,1,0,0,1,0,0,1]
})

# Removendo colunas que não devem ser usadas como features
X = df1.drop(columns=['transacao_id', 'cliente_id', 'valor_estornado', 'fraude'])
y = df1['fraude']

print(X)
print('-' * 30)
print(y)

   valor_compra  tempo_cliente
0           100             12
1           200             12
2            50              6
3            80              6
4           300             24
5           150             24
6           400             36
7           500             36
------------------------------
0    0
1    1
2    0
3    0
4    1
5    0
6    0
7    1
Name: fraude, dtype: int64

## Questão 02 (1.0)

a) Considere novamente o dataset abaixo. Se o problema for reformulado para o nível de cliente, explique como muda a unidade de análise, a variável-alvo e as variáveis explicativas.

b) Crie o DataFrame abaixo e, em seguida, agregue os dados por cliente_id, de forma que cada linha represente um cliente.
Construa um novo DataFrame com:

soma de valor_compra

quantidade de transações

manter tempo_cliente utilizando o primeiro valor por cliente

variável-alvo: indicar se o cliente teve ao menos uma fraude (valor 1 se sim, 0 caso contrário)

Não utilize a coluna valor_estornado na construção das variáveis explicativas.

Depois, separe X e y.

    'transacao_id': [1,2,3,4,5,6,7,8],
    'cliente_id':   [1,1,2,2,3,3,4,4],
    'valor_compra': [100,200,50,80,300,150,400,500],
    'tempo_cliente':[12,12,6,6,24,24,36,36],
    'valor_estornado': [0,200,0,0,300,0,0,500],
    'fraude':       [0,1,0,0,1,0,0,1]

### RESPOSTA

Item (2A)
A unidade de análise que antes era por transação passa a ser por cliente. E a variável-alvo agora é fraude do cliente, antes era fraude por transação. As variáveis explicativas mudam, porque agora estamos olhando valores agregados e não individuais

In [ ]:
# RESPOSTA Item (2B)
# Seu código abaixo:

import pandas as pd

# Criando o DataFrame
df2 = pd.DataFrame({
    'transacao_id': [1,2,3,4,5,6,7,8],
    'cliente_id': [1,1,2,2,3,3,4,4],
    'valor_compra': [100,200,50,80,300,150,400,500],
    'tempo_cliente': [12,12,6,6,24,24,36,36],
    'valor_estornado': [0,200,0,0,300,0,0,500],
    'fraude': [0,1,0,0,1,0,0,1]
})

df21 = df2.groupby('cliente_id').agg({
    'valor_compra': 'sum',
    'transacao_id': 'count',
    'tempo_cliente': 'first',
    'fraude': 'max'
}).reset_index()

# Separando X e y
X = df21.drop(columns=['cliente_id', 'fraude'])
y = df21['fraude']

print(X)
print(y)

   valor_compra  transacao_id  tempo_cliente
0           300             2             12
1           130             2              6
2           450             2             24
3           900             2             36
0    1
1    0
2    1
3    1
Name: fraude, dtype: int64

## Questão 03 (1.0)

a) O que é construção de atributos em análise preditiva?

b) No dataset abaixo, crie uma nova variável chamada valor_medio_por_compra dividindo o total gasto pela quantidade de compras.

    'cliente_id': [1,2,3,4],
    'total_gasto': [1000, 2000, 1500, 3000],
    'qtd_compras': [5, 10, 3, 6]

### RESPOSTA

Item (3A)
A contrução de atributos envolve gerar informações informações derivadas a partir das variáveis existentes, com o objetivo de produzir novas colunas com maior poder explicativo para o modelo

In [ ]:
# RESPOSTA Item (3B)
# Seu código abaixo:

df3 = pd.DataFrame({
    'cliente_id': [1,2,3,4],
    'total_gasto': [1000, 2000, 1500, 3000],
    'qtd_compras': [5, 10, 3, 6]
})

df3['valor_medio_por_compra'] = df3['total_gasto'] / df3['qtd_compras']

print(df3)

   cliente_id  total_gasto  qtd_compras  valor_medio_por_compra
0           1         1000            5                   200.0
1           2         2000           10                   200.0
2           3         1500            3                   500.0
3           4         3000            6                   500.0

## Questão 04 (1.0)

a) O que é codificação de variáveis categóricas e por que ela é necessária em modelos preditivos?

b) No dataset abaixo, aplique codificação One-Hot na variável tipo_pagamento.

    'cliente_id': [1,2,3,4],
    'tipo_pagamento': ['cartao', 'boleto', 'pix', 'cartao']

### RESPOSTA

Item (4A)
A codificação de variáveis categóricas é o processo de transformar valores categóricos em em valores numéricos. É necessária porque os modelos entendem números e não textos

In [ ]:
# RESPOSTA Item (4B)
# Seu código abaixo:

df4 = pd.DataFrame({
    'cliente_id': [1,2,3,4],
    'tipo_pagamento': ['cartao', 'boleto', 'pix', 'cartao']
})

df4_encoded = pd.get_dummies(df4, columns=['tipo_pagamento'])

print(df4_encoded)

   cliente_id  tipo_pagamento_boleto  tipo_pagamento_cartao  \
0           1                  False                   True
1           2                   True                  False
2           3                  False                  False
3           4                  False                   True

   tipo_pagamento_pix
0               False
1               False
2                True
3               False

## Questão 05 (1.0)

a) O que é codificação ordinal e em que tipo de variável ela deve ser aplicada?

b) No dataset abaixo, aplique codificação ordinal na variável nivel_cliente, considerando a ordem: baixo < medio < alto.

    'cliente_id': [1,2,3,4],
    'nivel_cliente': ['baixo', 'alto', 'medio', 'baixo']

### RESPOSTA

Item (5A)
A codificação ordinal transforma categorias em números inteiros, seguindo uma ordem ou hierarquia já definida entre elas

In [ ]:
# RESPOSTA Item (5B)
# Seu código abaixo:

df5 = pd.DataFrame({
    'cliente_id': [1,2,3,4],
    'nivel_cliente': ['baixo', 'alto', 'medio', 'baixo']
})

df5["nivel_cliente_ordem"] = df5["nivel_cliente"].map({
    "baixo": 1,
    "medio": 2,
    "alto": 3
})

df5.head()

   cliente_id nivel_cliente  nivel_cliente_ordem
0           1         baixo                    1
1           2          alto                    3
2           3         medio                    2
3           4         baixo                    1

## Questão 06 (1.0)

a) O que é normalização e qual seu objetivo no contexto de modelos preditivos?

b) No dataset abaixo, aplique normalização (Min-Max) na variável renda, transformando os valores para o intervalo [0,1].

    'cliente_id': [1,2,3,4],
    'renda': [2000, 5000, 3000, 4000]

### RESPOSTA

Item (6A)
É uma técnica de processamento de dados que serve para colocar valores numéricos na mesma escala, facilitando a comparação e o uso em modelos de machine learning

In [ ]:
# RESPOSTA Item (6B)
# Seu código abaixo:

df6 = pd.DataFrame({
    'cliente_id': [1,2,3,4],
    'renda': [2000, 5000, 3000, 4000]
})

# Normalização Min-Max.
df6["renda_normalizada"] = (df6["renda"] - df6["renda"].min()) / (df6["renda"].max() - df6["renda"].min())

df6[["renda","renda_normalizada"]]

   renda  renda_normalizada
0   2000           0.000000
1   5000           1.000000
2   3000           0.333333
3   4000           0.666667

## Questão 07 (1.0)

a) O que é padronização e qual a diferença em relação à normalização?

b) No dataset abaixo, aplique padronização (Z-score) na variável renda.

    'cliente_id': [1,2,3,4],
    'renda': [2000, 5000, 3000, 4000]

### RESPOSTA

Item (7A)
A padronização transforma os valores de uma variável para que passem a ter média 0 e desvio padrão 1. A padronização também não altera a forma da distribuição dos dados e reescala os valores da variável em
relação à média e ao desvio padrão.  

Diferente da normalização, ela não limita os dados a um intervalo fixo e é menos sensível a outliers

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df7 = pd.DataFrame({
    'cliente_id': [1,2,3,4],
    'renda': [2000, 5000, 3000, 4000]
})

# Aplicar padronização (StandardScaler).
scaler_std = StandardScaler()
df7['renda_padronizada'] = scaler_std.fit_transform(df7[['renda']])

print(df7[['renda', 'renda_padronizada']])

   renda  renda_padronizada
0   2000          -1.341641
1   5000           1.341641
2   3000          -0.447214
3   4000           0.447214

## Questão 08 (1.0)

a) O que é seleção de atributos e qual seu objetivo em análise preditiva?

b) No dataset abaixo, identifique e remova as variáveis que não devem ser utilizadas no modelo e, em seguida, separe X e y.

    'cliente_id': [1,2,3,4],
    'idade': [25, 40, 35, 50],
    'renda_mensal': [2000, 5000, 3000, 4000],
    'renda_anual': [24000, 60000, 36000, 48000],
    'inadimplente': [0,1,0,1]

### RESPOSTA

Item (8A)
A seleção de atributos mantém e identifica somente as variáveis mais importantes. Seu objetivo é deixar o modelo mais eficiente

In [ ]:
# RESPOSTA Item (8B)
# Seu código abaixo:

df8 = pd.DataFrame({
    'cliente_id': [1,2,3,4],
    'idade': [25, 40, 35, 50],
    'renda_mensal': [2000, 5000, 3000, 4000],
    'renda_anual': [24000, 60000, 36000, 48000],
    'inadimplente': [0,1,0,1]
})

X = df8.drop(columns=['cliente_id', 'renda_anual', 'inadimplente'])
y = df8['inadimplente']

print(X)
print('-' * 30)
print(y)

   idade  renda_mensal
0     25          2000
1     40          5000
2     35          3000
3     50          4000
------------------------------
0    0
1    1
2    0
3    1
Name: inadimplente, dtype: int64

## Questão 09 (1.0)

a) Como a correlação pode ser utilizada no processo de seleção de atributos?

b) Crie o DataFrame abaixo, calcule a matriz de correlação e, com base nela, identifique qual variável pode ser removida por redundância. Em seguida, remova essa variável, separe X e y e exiba o resultado.

    "idade": [22, 25, 28, 35, 45, 52, 30, 40],
    "renda": [2500, 3200, 4100, 5200, 7000, 8200, 4500, 6100],
    "anos_estudo": [12, 14, 16, 18, 16, 14, 15, 17],
    "tempo_empresa": [1, 2, 3, 6, 10, 15, 4, 8],
    "salario": [3000, 3500, 4500, 6000, 7200, 8000, 5000, 6500]

### RESPOSTA

Item (9A)
A correlação pode ser utilizada para identificar variáveis altamente correlacionadas entre si ou pouco relacionadas com a variável-alvo

In [ ]:
# RESPOSTA Item (9B)
# Seu código abaixo:


df9 = pd.DataFrame({
    "idade": [22, 25, 28, 35, 45, 52, 30, 40],
    "renda": [2500, 3200, 4100, 5200, 7000, 8200, 4500, 6100],
    "anos_estudo": [12, 14, 16, 18, 16, 14, 15, 17],
    "tempo_empresa": [1, 2, 3, 6, 10, 15, 4, 8],
    "salario": [3000, 3500, 4500, 6000, 7200, 8000, 5000, 6500]
})

df9.corr(numeric_only=True)["salario"].sort_values(ascending=False)



# Removendo variável redundante (renda, altamente correlacionada com salario)
df91 = df9.drop(columns=['renda'])

# Separando X e y (considerando salario como alvo)
X = df91.drop(columns=['salario'])
y = df91['salario']

print("\nX:\n", X)
print("-" * 30)
print("\ny:\n", y)

X:
    idade  anos_estudo  tempo_empresa
0     22           12              1
1     25           14              2
2     28           16              3
3     35           18              6
4     45           16             10
5     52           14             15
6     30           15              4
7     40           17              8
------------------------------

y:
 0    3000
1    3500
2    4500
3    6000
4    7200
5    8000
6    5000
7    6500
Name: salario, dtype: int64

## Questão 10 (1.0)

a) O que é informação mútua e como ela pode ser utilizada na seleção de atributos?

b) Crie o DataFrame abaixo, calcule a informação mútua entre as variáveis explicativas e a variável-alvo e identifique qual variável apresenta menor relevância. Em seguida, remova essa variável, separe X e y e exiba o resultado.

    "temperatura": [15,18,21,24,27,30,33,36,39],
    "marketing": [100,120,140,160,180,200,220,240,260],
    "renda_regiao": [2000,2100,2200,2300,2400,2500,2600,2700,2800],
    "vendas_sorvete": [180,250,330,420,520,630,750,880,1020]

### RESPOSTA

Item (10A)
A informação mútua mede o quanto uma variável ajuda a explicar a outra. Na seleção de atributos, indica quais variáveis são mais úteis para prever a variável-alvo

In [ ]:
# RESPOSTA Item (10B)
# Seu código abaixo:

df10 = pd.DataFrame({
    "temperatura": [15,18,21,24,27,30,33,36,39],
    "marketing": [100,120,140,160,180,200,220,240,260],
    "renda_regiao": [2000,2100,2200,2300,2400,2500,2600,2700,2800],
    "vendas_sorvete": [180,250,330,420,520,630,750,880,1020]
})

from sklearn.feature_selection import mutual_info_regression
import pandas as pd

X_temp = df10.drop(columns=['vendas_sorvete'])
y_temp = df10['vendas_sorvete']

mi_scores = mutual_info_regression(X_temp, y_temp, random_state=42)
mi_series = pd.Series(mi_scores, index=X_temp.columns).sort_values(ascending=True)

print("Informação Mútua de cada variável com 'vendas_sorvete':")
print(mi_series)

# Identificar a variável com menor relevância
least_relevant_variable = mi_series.index[0]
print(f"\nA variável com menor relevância é: {least_relevant_variable}")

# Remover a variável identificada
X = X_temp.drop(columns=[least_relevant_variable])
y = y_temp

print("\nX após remoção da variável menos relevante:")
print(X)
print("\ny (variável-alvo):")
print(y)

Informação Mútua de cada variável com 'vendas_sorvete':
renda_regiao    0.764153
temperatura     0.801190
marketing       0.801190
dtype: float64

A variável com menor relevância é: renda_regiao

X após remoção da variável menos relevante:
   temperatura  marketing
0           15        100
1           18        120
2           21        140
3           24        160
4           27        180
5           30        200
6           33        220
7           36        240
8           39        260

y (variável-alvo):
0     180
1     250
2     330
3     420
4     520
5     630
6     750
7     880
8    1020
Name: vendas_sorvete, dtype: int64